application: katholiekkwartetten
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
- url: /
  static_files: index.html
  upload: index\.html
- url: /stylesheets
  static_dir: stylesheets
- url: /javascript
  static_dir: javascript
- url: /stylesheets/images
  static_dir: stylesheets/images
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: lxml
  version: latest